---
title: "mp3"
author: "Kiara Correa Acosta"
date: "April 8, 2019"
output:
  html_document:
    code_folding: hide
---
Is this Hard Enough for you?
How Challenged do you want to be?
To be or not to be Challenged?

```{r, message = FALSE, warning = FALSE, include=FALSE, echo = TRUE}
library(tidyverse)
library(macleish)
library(sf)
```


```{r, message = FALSE, warning = FALSE, echo = TRUE}
trails_data <- macleish_layers %>%
  pluck("trails") %>%
  mutate(computed_length = st_length(geometry))

elevation_data <-macleish_layers %>%
  pluck("contours_3m") 
  
trails_elevation <- macleish_layers %>%
  pluck("trails") %>%
  mutate(computed_length = st_length(geometry)) %>%
  st_intersection(pluck(macleish_layers ,"contours_3m")) %>%
  group_by(name, computed_length) %>%
  summarize(elevation_gain = max(ELEV_FT) - min(ELEV_FT)) 

final_trails_elevation <- trails_elevation %>%
  group_by(name) %>%
  summarize(total_length = sum(computed_length), total_elevationg_gain = sum(elevation_gain))

```


^[[Link to the GitHub Repository](https://github.com/annabelyim/sds192-mp3.git]




Questions:
Our problem statement for this assigment is to analyze and classify the MacLeish trails in terms of difficulity. We will figure this out based on length and elevation of each trail and categorize them as "Easy", "Moderate" or "Difficult."